// Generated by the WebObjects Wizard Wed Sep 12 22:18:48 GMT 2001

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class Main extends WOComponent {


    public Main(WOContext context) {
        super(context);
    }


}
