// Generated by the WOLips Templateengine Plug-in at 22 déc. 2009 05:00:07
package your.app;

import com.webobjects.appserver.WOSession;

public class Session extends WOSession {
	private static final long serialVersionUID = 1L;

	public Session() {
	}
}
