// Generated by the WebObjects Wizard Mon Sep 10 12:26:28 GMT 2001

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public class LoginCheck extends WOComponent {


    public LoginCheck(WOContext context) {
        super(context);
    }


}
