// Generated by the WebObjects Wizard Mon Sep 10 10:49:23 GMT 2001

import com.webobjects.appserver.WOComponent;
import com.webobjects.eoaccess.EOUtilities;
import com.webobjects.eocontrol.EOEditingContext;
import com.webobjects.foundation.NSArray;
import com.webobjects.foundation.NSMutableDictionary;

public class LoginForm extends WOComponent {
  protected String username;
  protected String password;
  
  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username=username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public WOComponent login() {
    NSMutableDictionary lookup = new NSMutableDictionary();

    lookup.setObjectForKey(username.toLowerCase(), "loginname");
    lookup.setObjectForKey(password, "password");

    Session sess = (Session)session();

    EOEditingContext ec = sess.defaultEditingContext();
    NSArray result = EOUtilities.objectsMatchingValues(ec, "Customer", lookup);

    if (result.count() == 1) {
      sess.setUser( (Customer) result.objectAtIndex(0));
    }

    return null;
  }
}