// Generated by the WebObjects Wizard Thu Sep 13 12:42:21 GMT 2001

import com.webobjects.appserver.WOContext;

public class Main extends WROXComponent {

  public String getArea() {
    return "Home";    
  }

    public Main(WOContext context) {
        super(context);
    }


}
