// Generated by the WebObjects Wizard Fri Sep 14 17:44:17 GMT 2001

import com.webobjects.appserver.WOContext;

public class BooksTop extends WROXPage {
  protected String area = "Books";


    public BooksTop(WOContext context) {
        super(context);
    }


  public String getArea() {
    return area;
  }
  public void setArea(String newArea) {
    area = newArea;
  }

}
