// Generated by the WebObjects Wizard Fri Sep 14 17:44:34 GMT 2001

import com.webobjects.appserver.WOContext;

public class Checkout extends WROXPage {
  protected String area = "Checkout";


    public Checkout(WOContext context) {
        super(context);
    }


  public String getArea() {
    return area;
  }
  public void setArea(String newArea) {
    area = newArea;
  }

}
