// Generated by the WebObjects Wizard Fri Sep 14 17:44:26 GMT 2001

import com.webobjects.appserver.WOContext;

public class ElectronicsTop extends WROXPage {
  protected String area = "Electronics";


    public ElectronicsTop(WOContext context) {
        super(context);
    }


  public String getArea() {
    return area;
  }
  public void setArea(String newArea) {
    area = newArea;
  }

}
