// Generated by the WebObjects Wizard Fri Sep 14 17:19:20 GMT 2001

import com.webobjects.appserver.WOContext;

public class MenuBar extends WROXPage {
  public String area = "";

  public boolean isStateless() {
    return true;
  }
  
  public MenuBar(WOContext context) {
    super(context);
  }

  public String getArea() {
    return area;
  }
}
