// Generated by the WebObjects Wizard Fri Sep 14 17:44:09 GMT 2001

import com.webobjects.appserver.WOContext;

public class MusicTop extends WROXPage {
  protected String area = "Music";

    public MusicTop(WOContext context) {
        super(context);
    }


  public String getArea() {
    return area;
  }
  public void setArea(String newArea) {
    area = newArea;
  }

}
