// Generated by the WebObjects Wizard Fri Sep 14 14:05:25 GMT 2001

import com.webobjects.appserver.WOActionResults;
import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;
import com.webobjects.appserver.WORequest;
import com.webobjects.appserver.WOResponse;
import com.webobjects.foundation.NSArray;

public abstract class WROXComponent extends WOComponent {

    public WROXComponent(WOContext context) {
        super(context);
    }

  public abstract String getArea();

  public boolean synchronizesVariablesWithBindings() {
    if (isStateless()) {
      return false;
    }
    return true;
  }

  public void appendToResponse(WOResponse response, WOContext context) {
    if (synchronizesVariablesWithBindings ()) {
      pullBindings();
    }
    super.appendToResponse(response, context);
  }

  public void takeValuesFromRequest( WORequest request, WOContext context) {
    if (synchronizesVariablesWithBindings ()) {
      pullBindings();
    }
    super.takeValuesFromRequest(request, context);
  }

  public WOActionResults invokeAction(WORequest request, WOContext context) {
    if (synchronizesVariablesWithBindings ()) {
      pullBindings();
    }
    return super.invokeAction(request, context);
  }

  void pullBindings() {
    java.util.Enumeration enumerator = getBindingList().objectEnumerator();
    while(enumerator.hasMoreElements()) {
      String key = (String) enumerator.nextElement();
      takeValueForKey(valueForBinding(key), key);
    }
  }

  public NSArray getBindingList() {
    return NSArray.EmptyArray;
  }

  public void reset() {
    java.util.Enumeration enumerator = getBindingList().objectEnumerator();
    while(enumerator.hasMoreElements()) {
      String key = (String) enumerator.nextElement();
      this.takeValueForKey(null,key);
    }
  }
}
