// Generated by the WebObjects Wizard Fri Sep 14 14:04:22 GMT 2001

import com.webobjects.appserver.WOContext;

public class Main extends WROXPage {

  public String getArea() {
    return "Home";
  }
  
    public Main(WOContext context) {
        super(context);
    }


}
