// Generated by the WebObjects Wizard Fri Sep 14 14:05:25 GMT 2001

import com.webobjects.appserver.WOComponent;
import com.webobjects.appserver.WOContext;

public abstract class WROXComponent extends WOComponent {

    public WROXComponent(WOContext context) {
        super(context);
    }

  public abstract String getArea();
}
